{
 "title": "Deployment Frequency",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Deployments per App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployments per App (Namespace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "deployed_count", "legendFormat": "{{app}} ({{namespace}})" }
   ]
  },
  {
   "title": "24h Deployments Frequency per App (Namespace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(deployed_count[1d])", "legendFormat": "{{app}} ({{namespace}})" }
   ]
  },
  { "title": "Deployment Totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Last Year's Increase in Deployments Total per App (Namespace)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "increase(deployed_count[1y])", "legendFormat": "{{app}} ({{namespace}})" }
   ]
  },
  {
   "title": "Deployments Total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(deployed_count)" }
   ]
  },
  {
   "title": "Deployments per Namespace",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (namespace) (deployed_count)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}