apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-configmap
  namespace: {{ .Release.Namespace }}
data:
  exclude-regexp-pattern-names: ^local-path-provisioner$
  exclude-regexp-pattern-namespaces: ^kube-|^monitoring$|^{{ .Release.Namespace }}$
