apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-df-configmap
  namespace: k8s-df
data:
  exclude-regexp-pattern-names: ^local-path-provisioner$
  exclude-regexp-pattern-namespaces: ^kube-|^monitoring$|^k8s-df$
