apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-df
  name: k8s-df
  namespace: k8s-df
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-df
  template:
    metadata:
      labels:
        app: k8s-df
    spec:
      containers:
      - image: lttl.dev/k8s-df:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: k8s-df
#        livenessProbe:
#          httpGet:
#            scheme: HTTP
#            path: /healthy
#            port: 80
#          initialDelaySeconds: 1
#          periodSeconds: 3
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /ready
            port: 80
          initialDelaySeconds: 2
          periodSeconds: 5
        resources: {}
      serviceAccount: k8s-df-serviceaccount
      serviceAccountName: k8s-df-serviceaccount

