apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}-df
  name: {{ .Chart.Name }}-df
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-df
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-df
    spec:
      containers:
      - image: lttl.dev/{{ .Chart.Name }}-df:{{ .Values.image.version }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Chart.Name }}-df
        livenessProbe:
          httpGet:
            scheme: HTTP
            path: /ready # don't use /healthy here
            port: {{ .Values.ports.dfFrontend }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /ready
            port: {{ .Values.ports.dfFrontend }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits.cpu }}
            memory: {{ .Values.resources.limits.memory }}
          requests:
            cpu: {{ .Values.resources.requests.cpu }}
            memory: {{ .Values.resources.requests.memory }}        
      serviceAccount: {{ .Chart.Name }}-df-serviceaccount
      serviceAccountName: {{ .Chart.Name }}-df-serviceaccount

