apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-df-serviceaccount
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-df-role
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""] # core API group
  resources: ["configmaps"]
  resourceNames: ["k8s-df-configmap"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-df-rolebinding
  namespace: {{ .Release.Namespace }}
subjects:
- name: k8s-df-serviceaccount
  kind: ServiceAccount
  apiGroup: ""
roleRef:
  name: k8s-df-role
  kind: Role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: k8s-df-clusterrole
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: default
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-df-clusterrolebinding
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-df-clusterrole
subjects:
- kind: ServiceAccount
  name: k8s-df-serviceaccount
  namespace: {{ .Release.Namespace }}