apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-df
  name: {{ .Chart.Name }}-df-backend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.ports.dfBackend }}
    protocol: TCP
    targetPort: {{ .Values.ports.dfBackend }}
  selector:
    app: {{ .Chart.Name }}-df
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}-df
  name: {{ .Chart.Name }}-df-frontend
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: {{ .Values.ports.dfFrontend }}
    protocol: TCP
    targetPort: {{ .Values.ports.dfFrontend }}
  selector:
    app: {{ .Chart.Name }}-df
  type: ClusterIP
